import React, { useState } from 'react';
import ProductListPage from '../components/ProductListPage';
import '../styles/ProductUploadPage.css';

import Header from "../components/Header";

const ProductUploadPage = () => {
  const [productInfo, setProductInfo] = useState({
    id: '', // Added an id for key purposes
    title: '',
    price: '',
    coverImage: null,
    detailedDescription: '',
    shortDescription: '',
    descriptionFile: null,
    hashTag: ''
  });

  const [products, setProducts] = useState([]); // Store products in an array

  const handleChange = (e) => {
    const { name, value, files } = e.target;
    if (files) {
      setProductInfo({...productInfo, [name]: files[0]});
    } else {
      setProductInfo({...productInfo, [name]: value});
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    // Assuming you're adding an ID for each product. This is simplistic; in a real app, IDs might be generated by the backend.
    const newProduct = { ...productInfo, id: Date.now().toString() };
    setProducts([...products, newProduct]);
    console.log(newProduct);
    // Reset form if needed
    setProductInfo({
      id: '',
      title: '',
      price: '',
      coverImage: null,
      detailedDescription: '',
      shortDescription: '',
      descriptionFile: null,
      hashTag: ''
    });
  };

  return (
    <div>
      <Header />
      <form onSubmit={handleSubmit}>
        <input type="text" name="title" placeholder="Product Title" onChange={handleChange} />
        <input type="text" name="price" placeholder="Price" onChange={handleChange} />
        <input type="file" name="coverImage" onChange={handleChange} />
        <textarea name="detailedDescription" placeholder="Detailed Description" onChange={handleChange}></textarea>
        <textarea name="shortDescription" placeholder="Short Description" onChange={handleChange}></textarea>
        <input type="file" name="descriptionFile" onChange={handleChange} />
        <input type="text" name="hashTag" placeholder="Hash Tag" onChange={handleChange} />
        <button type="submit" className='upload'>Upload Product</button>
      </form>
      <ProductListPage products={products}/> {/* Pass the products as props */}
    </div>
  );
};

export default ProductUploadPage;
